### ISSUE TITLE
Add Raspberry Pi 5 Board

### ISSUE THREAD

**Issue by CameronBrooks11** [RalfLangeDresden/RaspberryPiCases#7]
Very subtle but relevant changes from RPi 4, namely: 
- Second camera port
- Reversed order of USB Ethernet ports
- Rearrangement of certain electrical chips (more of a visual than functional change)

**Comment by RalfLangeDresden** [comment]
Today I had add the Raspberry Pi 5 to the modules. Also the new HAT+ pcb is now available.

**Comment by CameronBrooks11** [comment]
Awesome, will take a look!
